### ISSUE TITLE
{{ }} doesn't work

### ISSUE THREAD

**Issue by edyu** [MommaWatasu/OteraEngine.jl#10]
I put `{{ name }}` in the template and made sure to put the following but it doesn't render properly:
<pre>
current.user.name = 'Test user'
init = Dict("name" => current.user.name, "img" => current.avatar)
return html(tmp(init))
</pre>
The template renders `{{ name }}` instead of `Test user`

**Comment by MommaWatasu** [comment]
I want you to give me more detail code(especially template) if you don't mind.

**Comment by edyu** [comment]
<pre>
&lt;div>
      &lt;div>
          &lt;img draggable="false" class="w-max h-max object-contain" src="{{ img }}" alt="Profile">
      &lt;/div>
      &lt;div>
          {{ name }}
      &lt;/div>
&lt;/div>

</pre>

**Comment by edyu** [comment]
Using triple backticks \``` \```  works but not `{{ }}`

**Comment by edyu** [comment]
It seems to be working on 2.0 so I'll close it for now.
