### ISSUE TITLE
{{ }} escapes html by default

### ISSUE THREAD

**Issue by edyu** [MommaWatasu/OteraEngine.jl#11]
It's not a good idea to escape by default for example:
`image = "http://example.com/image/test.jpg"`
`<img src="{{image}}">` will escape the path so the image will not be rendered.

I know it's probably too much work to implement {{ image | e }} for escaping but maybe it's ok when it's escaped for {{ }} because I can use \`\`\` image \`\`\`

**Comment by edyu** [comment]
It looks like even <pre>\`\`\` http://blahblah_hello \`\`\`</pre> is now doing html escaping and it also changed everything to lower case. It doesn't happen every time but sometimes it does. It got changed to <pre>http: blahblah hello</pre>

**Comment by MommaWatasu** [comment]
Sorry for waiting you. I mainly work on weekends, and it may take a few more days to fix the bugs(including other issue).
