### ISSUE TITLE
Changes environment

### ISSUE THREAD

**Issue by cbsteh** [MommaWatasu/OteraEngine.jl#15]
The following code works the first time, but running it the second time, fails:

```
using OteraEngine

init = Dict("user" => "Chris")
tmp = Template("template/template.html")
html = tmp(tmp_init=init)
```

The message I get after the first run is:
```
ERROR: ArgumentError: Package OteraEngine not found in current path, maybe you meant `import/using .OteraEngine`.
- Otherwise, run `import Pkg; Pkg.add("OteraEngine")` to install the OteraEngine package.
Stacktrace:
...
```

The reason is, after running the code the first time, `OteraEngine` resets my project environment to the default Julia @v1.9 environment. I believe the problem is line 91 in your `template.jl`: `Pkg.activate()`?

**Comment by MommaWatasu** [comment]
Thank you for your report. Your guess is correct, and I have an idea to fix this bug.
If my idea doesn't work, I'll add new argument which specify the environment.

**Comment by MommaWatasu** [comment]
Please upgrade OteraEngine to v0.2.3.
I couldn't find effective solution and I temporarily fix this issue, but `using` keyword is invalid inside the jl code block now.
