### ISSUE TITLE
Includes/template extension

### ISSUE THREAD

**Issue by frankier** [MommaWatasu/OteraEngine.jl#18]
Thanks for the package. It looks great and it's amazing it's so small. I think leaning heavily on having complicated stuff done in Julia and mainly working via generating Julia from syntax sugar and not introducing too much additional syntax is the reason for this and something you should stick with.

However, one thing that would be nice however is to have template inclusion, which is quite important for reusability.

In addition, the template extension concept is rather useful for generating nested formats like html, however this could get more complicated. Perhaps there is a nice way to just implement this on generating functions with default keyword arguments for base templates and having subtemplates call them with all generated block?

**Comment by MommaWatasu** [comment]
Hi @frankier ,

Sorry for the delayed response, and thanks for your suggestion. I'm not sure what syntax do you want me to add, but I guess you mean `{% extends %}`, `{% include %}` and `{% block %}`.
I'll implement this new syntax, and inform you know when I finish it.
If these syntax aren't what you expected, please let me know.

**Comment by frankier** [comment]
Yes that would be great!

**Comment by MommaWatasu** [comment]
Hi @frankier ,

I finished implement `extends` and `include`, and they are available in new v0.2.7.
Please look at the [document](https://mommawatasu.github.io/OteraEngine.jl/dev/tutorial/#Include-Template) for details.

**Comment by frankier** [comment]
Hi. This looks great! Sorry for being a bit slow getting back.

One wrinkle is that when using this with Oxygen.jl, I have a layout like so:

```
/entrypoint.jl
/src/myfile.jl
/templates/mytemplate.html
/templates/base.html
```

My PWD might be anything, but often the parent of `entrypoint.jl`. When I extend `base.html` in `mytemplate.html`, it won't be found since Julia will look in my PWD. There are two possible solutions here:

1. Simple solution: Try opening the file relative to its parent. Downside, it's possible for templates to be passed in as strings.
2. Flexible solution: Allow the user to pass a custom callback which is used to get the contents of the template. Then an integrating framework such as Oxygen.jl is responsible for making sure things are resolved relative to either the parent template or the templates directory.

**Comment by MommaWatasu** [comment]
Thanks for your suggestion. I think that the best solution is to create `dir` option in `ParserConfig`.
This option is initialized with either `pwd()` or parent directory of the given template file. But if you want to use other directory as template folder, you can change `dir` option with `config` or `config_path` argument.
I’ll implement this function.

**Comment by MommaWatasu** [comment]
Hi @frankier 

I released new version 0.3.0 a while ago.
In new version, the syntax is much more similar to Jinja2 and many functions are implemented.
Please look at the [docs](https://mommawatasu.github.io/OteraEngine.jl/dev/) for detail.

**Comment by frankier** [comment]
Thanks for letting me know. I'll check it out!

**Comment by MommaWatasu** [comment]
This issue has already been solved.
