### ISSUE TITLE
Current HEAD has typo nothing => Nothing

### ISSUE THREAD

**Issue by frankier** [MommaWatasu/OteraEngine.jl#19]
Here https://github.com/MommaWatasu/OteraEngine.jl/blob/master/src/template.jl#L28

Found while taking a peek at HEAD to replicate another (possible) bug.

**Comment by MommaWatasu** [comment]
Thank you for reporting. Now I'm greatly changing the implementation, and sometimes commit temporary. So, you don't have to worry if you found some bug. This bug is also fixed.

**Comment by frankier** [comment]
Ok thanks for letting me know.
