### ISSUE TITLE
Custom Parser

### ISSUE THREAD

**Issue by NegaScout** [MommaWatasu/OteraEngine.jl#22]
Hey!

Project looking good. I am also interested in templating packages, however I did not manage to write anything consistent. However, I wanted to implement parsing via [CombinedParsers.jl](https://gkappler.github.io/CombinedParsers.jl/dev/) and parsing expresions to Julia expr via Meta.parse() for easy evaluation via Meta.eval(). Maybe you find these ideas useful

**Comment by MommaWatasu** [comment]
Hi, @NegaScout .

Thank you for your suggestion.
I checked CombinedParser.jl and found it useful. However, CombinedParsers.jl is no longer maintained. The latest release was on two years ago. The current stable version of Julia is v1.9.4(and development of v1.10 is progressing), so v1.8, which is latest version supported by CombineParser.jl, is too old.
Thus, maybe I’ll develop own parser like that, but I don’t think I should use CombinedParser.jl itself.
If you know the alternative package(which is still maintained), please let me know.

**Comment by NegaScout** [comment]
There is also [Automa.jl](https://github.com/BioJulia/Automa.jl) (which is actively maintained), but it does not have such easy to use interface as CombinedParsers.jl imho

**Comment by MommaWatasu** [comment]
I implemented new parser with tokenizer. Thank you for your suggestion.
