### ISSUE TITLE
UTF-8 Bug

### ISSUE THREAD

**Issue by abriotde** [MommaWatasu/OteraEngine.jl#27]
When using utf-8 char in the template, parsing fail with a stack trace like this : 

> ERROR: LoadError: StringIndexError: invalid index [5205], valid nearby indices [5204]=>'à', [5206]=>' '
> Stacktrace:
>   [1] string_index_err(s::String, i::Int64)
>     @ Base ./strings/string.jl:12
>   [2] getindex
>     @ ./strings/string.jl:469 [inlined]
>   [3] tokenizer(txt::String, config::Main.OteraEngine.ParserConfig)
>     @ Main.OteraEngine ~/Documents/OpenProduct/OteraEngine.jl/src/parser.jl:14
>   [4] parse_template(txt::String, filters::Dict{String, Symbol}, config::Main.OteraEngine.ParserConfig)
>     @ Main.OteraEngine ~/Documents/OpenProduct/OteraEngine.jl/src/parser.jl:518
>   [5] Main.OteraEngine.Template(txt::String; path::Bool, filters::Dict{String, Symbol}, config_path::String, config::Dict{String, Union{Bool, String}})
>     @ Main.OteraEngine ~/Documents/OpenProduct/OteraEngine.jl/src/template.jl:59
>   [6] Template
>     @ ~/Documents/OpenProduct/OteraEngine.jl/src/template.jl:32 [inlined]
>   [7] (::var"#1#2")(f::IOStream)
>     @ Main ~/Documents/OpenProduct/openproduct-docs/communication/sendMail.jl:39
>   [8] open(::var"#1#2", ::String, ::Vararg{String}; kwargs::@Kwargs{})
>     @ Base ./io.jl:396
>   [9] open(::Function, ::String, ::String)
>     @ Base ./io.jl:393
>  [10] top-level scope
>     @ ~/Documents/OpenProduct/openproduct-docs/communication/sendMail.jl:37
> in expression starting at /home/alberic/Documents/OpenProduct/openproduct-docs/communication/sendMail.jl:37

**Comment by MommaWatasu** [comment]
Thanks for your Pull Request. Your PR has been merged and released as v0.5.1.
