### ISSUE TITLE
Is this limited to html?

### ISSUE THREAD

**Issue by feanor12** [MommaWatasu/OteraEngine.jl#3]
I think this template engine does not use any information, which restricts it to html.

So it would be great to use it for config files.

So to make it truly generic I think one would have to be able to configure the start and/or ending characters/strings of the code blocks. This would allow to avoid any collisions between the target syntax and the code blocks.

**Comment by MommaWatasu** [comment]
Thank you for your suggestion. I’ll make that change right away and release it.

**Comment by MommaWatasu** [comment]
I released new version, please use it.
If the new version is different from what you thought, write an new issue again.
