### ISSUE TITLE
Argument list is generated for every code block

### ISSUE THREAD

**Issue by feanor12** [MommaWatasu/OteraEngine.jl#4]
This part should also be able to work from outside the loop. It might make it a bit faster.

https://github.com/QGMW22/OteraEngine.jl/blob/588aa411004c91a737bca1e5cc2342de97e1908d/src/OteraEngine.jl#L80-L83

**Comment by MommaWatasu** [comment]
I didn't notice that. I'll cure it and release soon.

**Comment by MommaWatasu** [comment]
I fixed this problem and released new version. thank you for telling me this problem!
