### ISSUE TITLE
Template won't work if you use 'using'

### ISSUE THREAD

**Issue by edyu** [MommaWatasu/OteraEngine.jl#5]
Please don't abandon this repository.
This is actually useful for what I need. I'm using this to use templates with [Oxygen.jl](https://github.com/ndortega/Oxygen.jl). Some of your links don't work anymore and same with the example. You'll get the following error if you use
`using Dates
now()
`
<pre>
Error: ERROR:
│   exception =
│    syntax: "using" expression not at top level
│    Stacktrace:
│      [1] top-level scope
│        @ none:1
│      [2] eval
│        @ ./boot.jl:368 [inlined]
│      [3] eval
│        @ ~/.julia/packages/OteraEngine/oQ8sv/src/OteraEngine.jl:1 [inlined]
│      [4] (::Template)()
│        @ OteraEngine ~/.julia/packages/OteraEngine/oQ8sv/src/OteraEngine.jl:124
</pre>

**Comment by MommaWatasu** [comment]
Thank you for your contact!

I’m so busy(actually, I’m a Japanese high school student) that I haven’t maintained this package for long. But, I’m free today, and I’ll try to fix this issue.

@edyu
I have changed my user name, so I can’t apply update to main repository of Julia. Could you tell me the way to change user name registered in main repository?

**Comment by MommaWatasu** [comment]
I fixed this issue, and I want you to test(not ready for release at this time, so clone this repository).
If there is no problem and I found the way to change author name of main repository, I'll release new version.

**Comment by edyu** [comment]
Thank you. I appreciate your work. It's amazing you are doing such a great job while being a high school student. Anyways, you can always try to upload it with a new project name using a new username. You can even just call it Otera or OteraTemplate or JinjaTemplate or even OteraEngine2 (whatever you like). Let me know after you upload it and I'll test it out. 

Thank you.

**Comment by MommaWatasu** [comment]
I tried to change package name, but most (as you showed) names is invalid because of naming-guidelines. So, I’ll try making new PR by myself. Please wait until the new version is released.

**Comment by MommaWatasu** [comment]
I released new version(v0.2.0), and this issue was solved.

**Comment by MommaWatasu** [comment]
I released new version(v0.2.0), and this issue was solved.
