### ISSUE TITLE
{{ }} or {% %} doesn't seem to do anything

### ISSUE THREAD

**Issue by edyu** [MommaWatasu/OteraEngine.jl#6]
In jinja normally you'd use <pre>{{ }}</pre>and <pre>{% %}</pre> for code interpretation and it seems only <pre>\`\`\` \`\`\`</pre>works.

**Comment by MommaWatasu** [comment]
I don’t know whether you know that
```
``` ```
```
can be changed to whatever you like.

Certainly, the current function is so poor that I’ll improve it.
Please wait.

**Comment by edyu** [comment]
I do know <pre>\`\`\` \`\`\`</pre>. Originally I thought because it's a jinja template language it's it's in addition to these. I'll close this one and just focus on the other one. The reason for `{%` and `{{` is to be able to have control statements in `{%` and then variable substitution to work but I guess you can use \`\`\` to replace `{{ }}` but not `{%`.
