### ISSUE TITLE
Need to support real template usage

### ISSUE THREAD

**Issue by edyu** [MommaWatasu/OteraEngine.jl#7]
Let me give you an example:
<pre>
  &lt;div&gt;
    {% if "name" === "blahblah" %}
    &lt;div&gt;
      &lt;input type="text" name="name" value={{name}}&gt;
    &lt;/div&gt;
    {% end %}
  &lt;/div&gt;
</pre>
if <pre>init[name] == "blahblah"</pre>should render to
<pre>
  &lt;div&gt;
    {% if "name" === "blahblah" %}
    &lt;div&gt;
      &lt;input type="text" name="name" value="blahblah"&gt;
    &lt;/div&gt;
    {% end %}
  &lt;/div&gt;
</pre>
and if not then it should render to
<pre>
  &lt;div&gt;
  &lt;/div&gt;
</pre>

**Comment by edyu** [comment]
if you can make \`\`\` \`\`\` to work instead of {% %} that's fine but whatever works it needs to support this.

**Comment by MommaWatasu** [comment]
I made this package for my small project, so I didn’t mean to make a perfect template engine.
But, I’ll try to make this package more useful because there is other people who use it.

I think it’ll take at least one day, please wait.

**Comment by edyu** [comment]
I understand. 👍 You don't have to support {% %} or {{ }} but to make a template you do need some way to allowing {% if xxx=xxx %} something using {{ xxx }}  {% end %}. Otherwise, the use case of template language is very limited.

**Comment by MommaWatasu** [comment]
I finish implementing basic template usage(like `{%%}`). documentation hasn't been updated, but the syntax is simple.
When the template is
```
#HTML Template File
<html>
    <head><title>MyPage</title></head>
    <body>
        {% if name=="julia" %}
        The current time is <strong>
        ```
        using Dates
        now()
        ```
        </strong>
        {% end %}
        {% for i in 1 : 10 %}
        Hello Julia
        {% end %}
    </body>
</html>
```
the output will be(`init=Dict("name"=>"julia")`)
```
#HTML Template File
<html>
    <head><title>MyPage</title></head>
    <body>
        
        The current time is <strong>
        2023-05-03T23:02:59.753
        </strong>
        
        
        Hello Julia
        
        Hello Julia
        
        Hello Julia
        
        Hello Julia
        
        Hello Julia
        
        Hello Julia
        
        Hello Julia
        
        Hello Julia
        
        Hello Julia
        
        Hello Julia
        
    </body>
</html>
```
As you can see, I can't do things like removing extra spaces yet. Moreover, I've already found the fatal bug that variables don't work properly in for statement.
But, don't worry, solution for these problems has already been found and I'll fix when I have a enough time.
I'll temporarily release if the PR in General repository is merged.

**Comment by MommaWatasu** [comment]
I fixed bugs and made docs. please check the [docs](https://mommawatasu.github.io/OteraEngine.jl/dev/).

**Comment by edyu** [comment]
Are you going to release the new version? The current released version in the registry is still v0.1.3.

**Comment by edyu** [comment]
It looks like your new username is merged. Please release this.

**Comment by edyu** [comment]
Don't forget to update your new version to v0.1.4 or v.0.2.0 or whatever.

**Comment by MommaWatasu** [comment]
I think support for real template usage has done. If you have more idea to improve this package, please open a new issue.
