### ISSUE TITLE
Change version to v0.1.4 or v0.2.0 :)

### ISSUE THREAD

**Issue by edyu** [MommaWatasu/OteraEngine.jl#8]
Just a reminder, update your version. I can do a PR but that would be like taking credit for something I didn't do so you should do it. :)

**Comment by MommaWatasu** [comment]
Thank you for waiting. I released new version v0.2.0. please try it.
I'm worried about speed of processing because my parser is rough. I'll appreciate it if you tell me what you felt using new version.

**Comment by edyu** [comment]
I will. Thank you!
