### ISSUE TITLE
Put a link to your tutorial on the main document page towards the center

### ISSUE THREAD

**Issue by edyu** [MommaWatasu/OteraEngine.jl#9]
You wrote a very useful tutorial but it's linked from your document page at the bottom. It would be too hard for people to see. You should either replace your document with it or put another link to the tutorial at the middle so people can see it at first glance.

**Comment by edyu** [comment]
What I mean is to put it under `Resources` so people who went to your document page can see it right away. And make sure it's linked from your README.md too. Good job!

**Comment by MommaWatasu** [comment]
I added the link for Tutorial page in [this commit](https://github.com/MommaWatasu/OteraEngine.jl/commit/6cc02b2c3d3143d3e41e213c1e03c201bc81a713).
If what you mean was different, please explain your idea again.

**Comment by edyu** [comment]
You are correct but also put it here:
[https://mommawatasu.github.io/OteraEngine.jl/dev/](https://mommawatasu.github.io/OteraEngine.jl/dev/)

**Comment by MommaWatasu** [comment]
I put the link on Docs to, Thank you for your suggestion!
